# The previously used image:
# image: registry.gitlab.com/yade-dev/docker-yade
#
# Five new images:
# image: registry.gitlab.com/yade-dev/docker-yade:ubuntu16.04-py3
# image: registry.gitlab.com/yade-dev/docker-yade:ubuntu18.04
# image: registry.gitlab.com/yade-dev/docker-yade:debian-stretch
# image: registry.gitlab.com/yade-dev/docker-yade:debian-buster
# image: registry.gitlab.com/yade-dev/docker-yade:suse15
#
# Useful link to validator: https://gitlab.com/yade-dev/trunk/-/ci/lint


stages:
  - debpackages

# If you want to compile everything also on merge_request, change this template.
# If you want to compile on one platform see [1] note below.
.plaftorms_template: &platforms_definition
  only:
    - branches


# image: registry.gitlab.com/yade-dev/docker-yade:ubuntu18.04
# 6.1. build debian packages
.debpackages_template: &debpackages_definition
  <<: *platforms_definition
  stage: debpackages
  script:
    - apt update && apt install devscripts atool -y && ls -l && apt-get -y build-dep yade
    - git clone https://gitlab.com/yade-dev/yadedaily.git -b testdebpackages debian
    - dpkg-buildpackage -j8
#    - gbp buildpackage --git-ignore-branch --git-ignore-new
#    - gbp dch --ignore-branch --since=2019.01a

debpackages_18_04:
  <<: *debpackages_definition
  image: registry.gitlab.com/yade-dev/docker-yade:ubuntu18.04
