image: registry.gitlab.com/remche/docker-yade
stages:
  - cmake
  - build
  - test

cmake:
  stage: cmake
  script:
    - mkdir build && cd build
    - cmake -DSUFFIX=-ci -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=../install -DDISABLE_SAVE_TEMPS=1 ..
  artifacts:
    paths:
      - build
      
make:
  stage: build
  script:
    - cd build
    - make -j 16
    - make install
    - make clean
  artifacts:
    paths:
      - install
  dependencies: 
    - cmake      

test:
  stage: test
  script:
    - install/bin/yade-ci --test
  dependencies:
    - make


check:
  stage: test
  script:
    - install/bin/yade-ci --checks
  dependencies:
    - make


