# The previously used image:
# image: registry.gitlab.com/yade-dev/docker-yade
#
# Five new images:
# image: registry.gitlab.com/yade-dev/docker-yade:ubuntu16.04-py3
# image: registry.gitlab.com/yade-dev/docker-yade:ubuntu18.04
# image: registry.gitlab.com/yade-dev/docker-yade:debian-stretch
# image: registry.gitlab.com/yade-dev/docker-yade:debian-buster
# image: registry.gitlab.com/yade-dev/docker-yade:suse15
#
# Useful link to validator: https://gitlab.com/yade-dev/trunk/-/ci/lint


stages:
  - deb

# image: registry.gitlab.com/yade-dev/docker-yade:ubuntu18.04
# 6.1. build debian packages
.deb_template: &deb_definition
  stage: deb
  only:
    - branches
  script:
    - apt-get update && apt-get -y build-dep .
    - export JOBSNUM=$(case $CI_RUNNER_DESCRIPTION in
        "y_4pak_64cpu_256RAM_4TB_docker") echo "42" ;;
        "c_4pak_64cpu_256RAM_4TB_docker") echo "42" ;;
        "y_6pak_48cpu_128RAM_4TB_docker") echo "42" ;;
        "c_6pak_48cpu_128RAM_4TB_docker") echo "42" ;;
        "y_7pak_48cpu_128RAM_1TB_docker") echo "42" ;;
        "c_7pak_48cpu_128RAM_1TB_docker") echo "42" ;;
        "yade-runner") echo "12" ;;
        "yade-runner-01") echo "1" ;;
        *) echo "8";;
        esac)
    - echo $JOBSNUM
    - dpkg-buildpackage -j$JOBSNUM
    - cd ..
    - rm -rf yadedaily
    - ls -l

deb_buster:
  <<: *deb_definition
  image: registry.gitlab.com/yade-dev/docker-yade:debian-buster
  before_script:
    - ./scripts/ppa_ci/builddeb.py -d "buster"
    - cd deb_buster/yadedaily
  artifacts:
    paths:
      - ../deb_buster
    expire_in: 2 hours