image: registry.gitlab.com/yade-dev/docker-yade

stages:
  - cmake
  - build
  - test
  - doc
  - pages

# https://docs.gitlab.com/ee/ci/yaml/#onlyexcept-basic
# I create two "stage: cmake" instructions.
# only: master        will use -DCHUNKSIZE=1, to avoid future compilation errors caused by DCHUNKSIZE other than 1
# only: merge_request will use -DCHUNKSIZE=4, to make compilation faster by 3 minutes
cmake:
  stage: cmake
  only:
    - master
  script:
    - mkdir build && cd build
    - cmake -DSUFFIX=-ci -DCMAKE_VERBOSE_MAKEFILE=ON -DCHUNKSIZE=1 -DCMAKE_INSTALL_PREFIX=../install -DDISABLE_SAVE_TEMPS=1 ..
  artifacts:
    paths:
      - build

cmake:
  stage: cmake
  only:
    - merge_request
  script:
    - mkdir build && cd build
    - cmake -DSUFFIX=-ci -DCMAKE_VERBOSE_MAKEFILE=ON -DCHUNKSIZE=4 -DCMAKE_INSTALL_PREFIX=../install -DDISABLE_SAVE_TEMPS=1 ..
  artifacts:
    paths:
      - build

make:
  stage: build
  only:
    - master
    - merge_request
  script:
    - export JOBSNUM=$(case $CI_RUNNER_DESCRIPTION in "y_4pak_64cpu_256RAM_4TB_docker") echo "43" ;; "c_4pak_64cpu_256RAM_4TB_docker") echo "43" ;; "c_6pak_48cpu_128RAM_4TB_docker") echo "45" ;; "y_6pak_48cpu_128RAM_4TB_docker") echo "45" ;; "yade-runner") echo "12" ;; "yade-runner-01") echo "1" ;; *) echo "3";; esac)
    - echo $JOBSNUM
    - cd build
    - make -j $JOBSNUM
    - make install
    - make clean
  artifacts:
    paths:
      - install
  tags:
    - fast
  dependencies:
    - cmake

test:
  stage: test
  only:
    - master
    - merge_request
  script:
    - install/bin/yade-ci --test
  dependencies:
    - make

check:
  stage: test
  only:
    - master
    - merge_request
  script:
    - install/bin/yade-ci --checks
  dependencies:
    - make

doc:
  stage: doc
  only:
    - master
    - merge_request
  script:
    - cd build
    - xvfb-run -s "-screen 0 1600x1200x24" make doc
  dependencies:
    - cmake
    - make
  artifacts:
    paths:
      - install

pages:
  stage: pages
  only:
    - master
  script:
    - mv install/share/doc/yade-ci/html public
    - mv install/share/doc/yade-ci/Yade.pdf public
    - mv install/share/doc/yade-ci/Yade.epub public
  dependencies:
    - doc
  artifacts:
    paths:
      - public

