variables:
  CCACHE_WORK_DIR: $CI_PROJECT_DIR/.ccache

stages:
  - deb

# image: registry.gitlab.com/yade-dev/docker-yade:ubuntu18.04
# 6.1. build debian packages
.deb_template: &deb_definition
  stage: deb
  only:
    - branches
  script:
    - cd $CI_PROJECT_DIR/deb/yadedaily
    - apt-get update && apt-get -y build-dep .
    - export JOBSNUM=$(case $CI_RUNNER_DESCRIPTION in
        "y_4pak_64cpu_256RAM_4TB_docker") echo "43" ;;
        "c_4pak_64cpu_256RAM_4TB_docker") echo "43" ;;
        "y_6pak_48cpu_128RAM_4TB_docker") echo "46" ;;
        "c_6pak_48cpu_128RAM_4TB_docker") echo "46" ;;
        "y_7pak_48cpu_128RAM_1TB_docker") echo "46" ;;
        "c_7pak_48cpu_128RAM_1TB_docker") echo "46" ;;
        "yade-runner") echo "12" ;;
        "yade-runner-01") echo "1" ;;
        *) echo "8";;
        esac)
    - echo $JOBSNUM
    - export CCACHE_DIR=${CCACHE_WORK_DIR}
    - DEB_BUILD_OPTIONS=noddebs dpkg-buildpackage -j$JOBSNUM
    - ccache -s
    - rm -rf $CI_PROJECT_DIR/deb/yadedaily
    - ls -l $CI_PROJECT_DIR/deb
  artifacts:
    paths:
      - ./deb
    expire_in: 1 day
  cache:
    paths:
      - ${CCACHE_WORK_DIR}


deb_buster:
  <<: *deb_definition
  image: registry.gitlab.com/yade-dev/docker-yade:debian-buster
  before_script:
    - rm -rf ./deb
    - ./scripts/ppa_ci/builddeb.py -d "buster"

deb_stretch:
  <<: *deb_definition
  image: registry.gitlab.com/yade-dev/docker-yade:debian-stretch
  before_script:
    - rm -rf ./deb
    - ./scripts/ppa_ci/builddeb.py -d "stretch"

deb_bionic:
  <<: *deb_definition
  image: registry.gitlab.com/yade-dev/docker-yade:ubuntu18.04
  before_script:
    - rm -rf ./deb
    - ./scripts/ppa_ci/builddeb.py -d "bionic"
